### ISSUE TITLE
ClassCastException in TimeoutWiederholungHttpInvokerRequestExecutor in isy-serviceapi-core:3.0.1 bei Nutzung von isy-sicherheit-keycloak

### ISSUE THREAD

**Issue by HannoRidder** [IsyFact/isyfact-standards#381]
Im TimeoutWiederholungHttpInvokerRequestExecutor in isy-serviceapi-core:3.0.1 kommt es zu einer ClassCastException in der Methode prepareConnection (Zeile 133), wenn isy-sicherheit anstelle von isy-security verwendet wird. Der Spring Security Context wird auf die Klasse **AbstractOAuth2TokenAuthenticationToken** aus **isy-security** gemappt. Dies passt nicht zur Implementierung von **isy-sicherheit-keycloak**, da dort eine andere Implementierung genutzt wird.

Der Fehler kann vermieden werden, indem in der Fallunterscheidung zwischen Nutzung von Aufrufkontext und Spring Security Context die Reihenfolge vertauscht wird. Mit folgender Variante funktioniert es:

```
if (this.aufrufKontextVerwalterOptional.isPresent()) {
    bearerToken = this.aufrufKontextVerwalterOptional.get().getBearerToken();
} else if (SecurityContextHolder.getContext() != null
    && SecurityContextHolder.getContext().getAuthentication() != null) {
    Authentication currentAuthentication = SecurityContextHolder.getContext().getAuthentication();
    bearerToken = ((AbstractOAuth2TokenAuthenticationToken<?>) currentAuthentication).getToken()
        .getTokenValue();
}
```

**Comment by frgreiner** [comment]
@HannoRidder 
wurde mit: https://github.com/IsyFact/isyfact-standards/pull/487 gelöst. Geplante Lösungsversion ist IsyFact 3.1.0

Um die Exception auch in anderen Fällen zu vermeiden haben wir das erste if-Statement erweitert und prüfen mit `instanceof` ob ein kompatibler Token Typ vorliegt.

 Vielen Dank für die Beschreibung und deine Unterstützung!
